### ISSUE TITLE
jest and babel-jest is missing in package.json?

### ISSUE THREAD

**Issue by manask88** [ncuillery/rn-diff#11]
When I do react-native init XX locally, I get jest dependencies.
AS of rn 0.42.0, I get babel-jest and also jest
from 0.41.2 to 0.42.0 versions for both libraries were updated.
It looks like those changes were not caught in your diff
Is there any reason why?

**Comment by pvinis** [comment]
i think we should actually try to create a new app, and diff it with the latest one here, and see the differences. maybe there are stuff we are missing.
thanks for the report.

**Comment by ncuillery** [comment]
Sorry to have left this issue unanswered for a long time.

I did some research in the RN repo. As far as I remember, jest and babel-jest has been add in the init template, but for retro-compatibility reason, the upgrade command checks the presence of these 2 libs and doesn't upgrade the Jest related stuff if it is not already present.

The RnDiffApp used in this repo has been generated a loooooong time ago (RN 0.26), Jest wasn't included at this time, and it has never been added.
