### ISSUE TITLE
0.45.0 is out

### ISSUE THREAD

**Issue by pvinis** [ncuillery/rn-diff#16]

**Comment by ncuillery** [comment]
Done, thanks 👍

**Comment by pvinis** [comment]
thank you. sorry for the annoying issues :(.
is it easy to actually do this with a script or something? so you dont even need to do anything to create the new diff?

**Comment by ncuillery** [comment]
Well, there is a script that works pretty well: https://github.com/ncuillery/rn-diff/blob/master/new-version.sh
So it's a (almost) a one-step operation.

At the beginning I planned to trigger the script on every release automatically (I think we can achieve something like that with Travis CI) but I'm not sure it's a good idea anymore. A human look could be useful before pushing the branch.

Are you interested to become a contributor with me and @ryankask ? We could be more reactive in case of new release. It would require about 5 minutes to push a new diff.

**Comment by pvinis** [comment]
i definitely would. sorry for the late reply. i always see the messages, but i answer in batches when its not super important.
