### ISSUE TITLE
Can we upgrade by using the master repo of react-native?

### ISSUE THREAD

**Issue by SudoPlz** [ncuillery/rn-diff#17]
What the title says :)

**Comment by pvinis** [comment]
so you mean to have a diff from latest release and react-native master?

**Comment by SudoPlz** [comment]
I mean instead of passing a version to the cli tool, pass the word master and have it diff against the master repo.

**Comment by pvinis** [comment]
right. i guess it is possible. dont know how useful it is, but i can try it in the weekend.
(fellow greek btw :D)

**Comment by SudoPlz** [comment]
The reason I needed that is because some features where not released yet, but they existed on the master branch at that time. The problem was I had no way to automatically upgrade to the master branch.

**Comment by pvinis** [comment]
i understand that, and i also needed that, but i ended up forking so i can control a few things. using master is a bit too risky sometimes. but yea, i get it. i will try in the weekend.
