### ISSUE TITLE
0.48 is out for 4 days :)

### ISSUE THREAD

**Issue by SandroMachado** [ncuillery/rn-diff#18]
```
However I recognize I sometimes need to get my ass kicked, so please, post such
an issue if the release is out for more than 2 or 3 days!
```
:)

If you want I can make a PR with the changes.

**Comment by ncuillery** [comment]
Done, thanks :)

**Comment by SandroMachado** [comment]
Great! 👍

**Comment by ncuillery** [comment]
>If you want I can make a PR with the changes.

Actually, you can't, see https://github.com/ncuillery/rn-diff#how-can-i-contribute-

**Comment by SandroMachado** [comment]
True, I didn't read that.

**Comment by pvinis** [comment]
this commit 053fe6cfd0ace214fd39f82aa1bbbbb5766a14a8 was there since 1st of sept..
