### ISSUE TITLE
Version 0.32

### ISSUE THREAD

**Issue by ryankask** [ncuillery/rn-diff#2]
RN 0.32 is now released after a little delay. Do you plan to add a branch?

By the way, this is one of the most useful RN related projects. Thanks!

**Comment by ncuillery** [comment]
Ahah it's fun you asked because I was making some tests just few minutes ago with a colleague of mine (#1) in order to see if anybody can contribute in the classic way (fork / PR)... and it would appear not 😿 

I'll do this soon by myself, like, **very** soon.

**Comment by ryankask** [comment]
Awesome 👍

Have you thought about automating it? There is a release feed https://github.com/facebook/react-native/releases.atom.

I might have a look at this in the next few weeks if you don't have time.

**Comment by ncuillery** [comment]
Here you are:
https://github.com/ncuillery/rn-diff/compare/rn-0.31.0...rn-0.32.0

~~Nothing except the React upgrade~~ see below

**Comment by ryankask** [comment]
Nice! Should be straightforward then... maybe.

**Comment by ncuillery** [comment]
Well, be careful the 0.32.0 upgrade seems to introduce few changes in `.flowconfig`. The bash script I use to create new branches didn't reveal that (https://github.com/ncuillery/rn-diff/compare/rn-0.31.0...rn-0.32.0 shows only 1 change in `package.json`). I have to dig into that.

**Comment by ncuillery** [comment]
I fixed the script, https://github.com/ncuillery/rn-diff/compare/rn-0.31.0...rn-0.32.0 presents the whole changes now (like I said, only `.flowconfig` is changed).
