### ISSUE TITLE
Question: If I am in a very old react-native version, I need to look diff by diff, looking into versions and change the files or theres an easy way?

### ISSUE THREAD

**Issue by djalmaaraujo** [ncuillery/rn-diff#20]
Question: If I am in a very old react-native version, I need to look diff by diff, looking into versions and change the files or there's an easy way?

Ex: I was in react-native 0.40, and I upgraded to the latest one.. the app is running fine, my I always think.. is something missing?

**Comment by ncuillery** [comment]
Did you upgrade with `react-native-git-upgrade` ?

If the tool upgraded your code base without conflict or easy-to-solve conflicts and your app works well, you are good to go 😎

This repo is useful for more complicated use cases:
- When `react-native-git-upgrade` has produced huge conflicts that require a deep understanding of what has changed in the React Native template files.
- People who don't want or can't use `react-native-git-upgrade` (when React Native is integrated in an existing app that hasn't been generated with `react-native init` for example)

**Comment by djalmaaraujo** [comment]
@ncuillery Hello, thanks for this fast response. I used, but the tool has a bug where it changes all the node_modules/ dependencies, but it didn't update the src/ files, which is crazy. It's a known bug.. 

In the end, everything is working as expected, I just feel like it could be better, hehe.

I might re-create the project using the create-reactive-native-app tool to remove this uncertain from my head. :)

**Comment by ncuillery** [comment]
Yeah, `react-native-git-upgrade` has some issues for what I unfortunately don't have time to fix these days.
