### ISSUE TITLE
Single entry point for both iOS and Android

### ISSUE THREAD

**Issue by mattfysh** [ncuillery/rn-diff#21]
The breaking change released as part of v0.49.0 is not currently reflected in the tags. Take a look at the beginning of the release notes here: https://github.com/facebook/react-native/releases/tag/v0.49.0

**Comment by ncuillery** [comment]
Thanks for reporting this @mattfysh 👍

I've decided to not report the change manually to be consistent with the upgrade tool (and because it'd be boring to rewrite the 10 commits since that release 😇). But I've added some documentation in the README.md file.
