### ISSUE TITLE
Create Diffs for 0.52.0

### ISSUE THREAD

**Issue by EyMaddis** [ncuillery/rn-diff#25]
First off: thanks for your dedication and a happy new year!

[**0.52.0**](https://github.com/facebook/react-native/releases/tag/v0.52.0) is out for almost a month and I would love to use your tool again!

**Comment by ujwal-setlur** [comment]
So, I am little confused. on react-native's [home](https://facebook.github.io/react-native/versions.html) page, 0.52.0 is still tagged as 0.52-RC. Is it really officially out?

**Comment by awinograd** [comment]
Looks like that linked page is behind. The official release is out on github

https://github.com/facebook/react-native/releases/tag/v0.52.0

**Comment by dino115** [comment]
I've forked the repo and added 0.52.0, for now you can use this diff:

https://github.com/dino115/rn-diff/compare/rn-0.51.0...rn-0.52.0


By the way, it is very easy to do it by your own.

1. fork and clone repo
2. use the new-version script
    ```bash
    ./new-version.sh rn-0.51.0 0.52.0
    ```
3. click on the compare link generated in the readme
4. replace the github username in the url

I hope this repo will be maintained for future versions. Thanks for the idea and your great work!

**Comment by ryankask** [comment]
I've tried generating a new branch by running a `new_version.sh` but the diff doesn't look like @dino115's, even after a fresh clone of rn-diff.

I'll try again soon and sorry about the delay.

**Comment by ncuillery** [comment]
I've just pushed the 0.52.0 and 0.52.1 branches. Thanks @dino115 to have brought the update during the delay, sorry for that 🙄

@ryankask that's curious, have you figured out why you had a difference? (no problem from my side)
