### ISSUE TITLE
Wrong diff since 0.54.3

### ISSUE THREAD

**Issue by ncuillery** [ncuillery/rn-diff#27]
There are some problems with the recent branches:
- `rn-0.54.3` as the same history of the `rn-0.54.2`
![image](https://user-images.githubusercontent.com/4425455/38460693-0a9dbbf4-3a8d-11e8-88e6-d2b93233c7ae.png)
(there is always a commit with the `package.json` update, even if there is no RN changes)
- `rn-0.54.4` has been created from master, it should have been created from the previous version (`rn-0.54.3`)
![image](https://user-images.githubusercontent.com/4425455/38460724-ae6c32b0-3a8d-11e8-801b-a4f8a7155abd.png)
The `master` branch and the `rn-0.xx.x` branches are 2 different things.
- `rn-0.55.0` has the same history as `rn-0.54.4`

Let me re-write these branches, in the meanwhile, the corresponding diffs are not relevant ⚠️

**Comment by ncuillery** [comment]
Everything is in order now. The diff from 0.54.x to 0.55.0 is correct (and huge!).

**Comment by chadlwilson** [comment]
Thanks!

**Comment by pvinis** [comment]
i might have something to do with that. if i was, @ncuillery, im sorry.

**Comment by ncuillery** [comment]
No problem @pvinis. The 0.55.2 update was correct 🙂Thanks

I just pushed the 0.55.3 update

**Comment by pvinis** [comment]
i didnt have the react-native-git-upgrade installed, so the script complained and moved on. ill change the script to fail when that happens.
