### ISSUE TITLE
Upgrade from RN 0.51.0 to 0.55.3

### ISSUE THREAD

**Issue by odesey** [ncuillery/rn-diff#28]
Like the title says I am attempting to upgrade from RN 0.51.0 to 0.55.3 by doing the following:

`curl https://github.com/ncuillery/rn-diff/compare/rn-0.51.0...rn-0.55.3.diff > upgrade-rn.patch`
`appNameCamelCase=MyCoolApp`
`appNameLowerCase=mycoolapp`
`sed -i "" "s-ios/RnDiffApp-ios/${appNameCamelCase}-" upgrade-rn.patch`
`sed -i "" "s-java/com/rndiffapp-java/com/${appNameLowerCase}-" upgrade-rn.patch`
`git remote add rn-diff https://github.com/ncuillery/rn-diff.git` only did this once
`git fetch rn-diff`
`git apply upgrade-rn.patch --exclude=package.json -p 2 --3way`

I then get the following:
```log
error: patch failed: .flowconfig:16
Falling back to three-way merge...
Applied patch to '.flowconfig' with conflicts.
error: patch failed: .gitignore:51
Falling back to three-way merge...
Applied patch to '.gitignore' with conflicts.
error: patch failed: android/app/src/main/AndroidManifest.xml:1
Falling back to three-way merge...
Applied patch to 'android/app/src/main/AndroidManifest.xml' with conflicts.
error: patch failed: ios/MyCoolApp.xcodeproj/project.pbxproj:25
Falling back to three-way merge...
Applied patch to 'ios/MyCoolApp.xcodeproj/project.pbxproj' with conflicts.
error: ios/GenesisAppMobileTests/RnDiffAppTests.m: does not exist in index
```

When I browse to the files with the merge conflicts, there is nothing to accept/reject...no proposed changes.

Now if I repeat the previous steps this time going from RN 0.51.0 to 0.52.2, I get the following:

```
error: patch failed: .flowconfig:16
Falling back to three-way merge...
Applied patch to '.flowconfig' with conflicts.
error: patch failed: ios/GenesisAppMobile.xcodeproj/project.pbxproj:25
Falling back to three-way merge...
Applied patch to 'ios/MyCoolApp.xcodeproj/project.pbxproj' with conflicts.
U .flowconfig
U ios/MyCoolApp.xcodeproj/project.pbxproj
```
This time however, I can see the proposed changes in each of the files and manually accept them.

However, once I accept the changes I get this error when I try to upgrade again (like from RN 0.52.2 to 0.53.3):

```
error: .flowconfig: does not exist in index
```
It does not go any further. (whether I accept then proposed changes or not, same result)

**Comment by jln-dk** [comment]
+1

**Comment by yanniser** [comment]
did you try to create an empty .flowconfig ?

**Comment by odesey** [comment]
@yanniser , yes I tried that as well. It didn't make any difference.
