### ISSUE TITLE
What is the recommended way to update project.pbxproj file for the app

### ISSUE THREAD

**Issue by varungupta85** [ncuillery/rn-diff#29]
Hi,

Sometimes, the `project.pbxproj` is updated to contain some new dependencies or updates to the existing dependencies. What is the recommended way to update this file? I don't think it I can just copy and paste the changes shown in the diff because it may create some duplicates or create some conflicting entries in the file.

**Comment by Lukkub** [comment]
Hi,
So currently I did a big upgrade from old rn-0.44 version to the newest one and the `project.pbxproj` file was the most stressful thing to work with.
Fortunately I did it - worked with this repo.
So from my experience, it is possible to update it manually but you need to be very careful and you must understand what you do.

### !! Always modify `project.pbxproj` taking into account your project specific changes. !!
