### ISSUE TITLE
0.57.3, 0.57.4

### ISSUE THREAD

**Issue by raphaelhovsepyan** [ncuillery/rn-diff#39]
It's just a reminder that new 2 versions are released 18 days ago and 5 day ago

**Comment by pvinis** [comment]
I kinda gave up on this repo, mostly because I have always found git upgrade very awkward and troublesome. I have https://GitHub.com/pvinis/rn-diff-purge if you are interested, which is easier for me to keep up, and use.

--  
Pavlos Vinieratos

**Comment by raphaelhovsepyan** [comment]
awesome thanks

**Comment by MrHubble** [comment]
@pvinis In your repo I see you link to the the procedure as described by in this repo?

>The procedure isn't really straightforward but it's still more efficient than using the upgrade command:
1 Download the git patch
2 Prepare the patch
3 Set up the 3-way merge
4 Run the apply command

Is it safe to assume that that's how you're using [rn-diff-purge](
https://github.com/pvinis/rn-diff-purge)?

**Comment by pvinis** [comment]
op. where is that? ill make sure to change it. i have changed the script and it deletes the old and creates a new project and then diffs.

**Comment by pvinis** [comment]
I have updated the readme. if there is any place that still references this repo's way, let me know.

**Comment by MrHubble** [comment]
This is where it links to the usage details:

<img width="988" alt="screen shot 2018-11-02 at 4 42 44 pm" src="https://user-images.githubusercontent.com/2251631/47896197-6b4b8a80-dec0-11e8-868c-402a5685f4b7.png">

**Comment by pvinis** [comment]
should be all fine now. also, sorry to "pollute" this repo's issues for this. and thanks for pointing out the errors on my repo. :)

**Comment by MrHubble** [comment]
Thanks for the new repo and for the clarification. Apparently `react-native-git-upgrade` is not well maintained so I'm looking forward to using your alternative.

**Comment by pvinis** [comment]
it has been a hard problem for a while now. that's what lead me to rn-diff and I'm thankful for this repo, but often I was doing the purge thing in addition, to make sure I'm not missing something. so now I am not depending on git-upgrade at all, and do it my way, which in my opinion is the cleanest way.

let me know of any concerns/suggestions, over at the purge repo.

I'm happy if it's useful for more people than just me! :D
