### ISSUE TITLE
RN 0.35?

### ISSUE THREAD

**Issue by GantMan** [ncuillery/rn-diff#4]
Hiya!  Where's the patch for 0.35?

Is this not automated?

**Comment by sibelius** [comment]
u could run this script `new-version.sh` https://github.com/ncuillery/rn-diff/blob/master/new-version.sh

but there is no instructions of how to run it

**Comment by ryankask** [comment]
I've pushed this now. Sorry for the delay. Looks like you just need to bump the RN version.
