### ISSUE TITLE
0.58.0 released

### ISSUE THREAD

**Issue by chris-feist** [ncuillery/rn-diff#40]
**However I recognize I sometimes need to get my ass kicked, so please, post such
an issue if the release is out for more than 2 or 3 days!**

![ass kicking](https://media1.tenor.com/images/74b79a7dc96b93b0e47adab94adcf25c/tenor.gif?itemid=8217719)

**Comment by mikehardy** [comment]
You will probably do better examining this: https://github.com/pvinis/rn-diff-purge

**Comment by pvinis** [comment]
now with 0.59.0-rc.0 and hooks! https://github.com/pvinis/rn-diff-purge#hooks

**Comment by chris-feist** [comment]
@pvinis you da man/woman! Closing this issue in favor of your repo
