### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by mgtitimoli** [ncuillery/rn-diff#7]
Hi Nicolas,

Before going further I would like to thank you for the effort you spent on this, great work!

What are your thoughts about the possibility of creating a **CLI** that reads your _package.json_, and present a menu which all the versions greater than the one you have and let you select the one you want and then apply the corresponding **patch** with `git apply`?

It could also modify your _package.json_ replacing your current version with the one selected...

**Comment by ncuillery** [comment]
Hi, thanks for your kind words 😄 

I'm not sure we should handle the list of versions, npm commands already do that (`npm outdated`, `npm view react-native@latest`, `npm view react-native versions`, ...).

I recently submit a PR on the RN repo, it adds a CLI focused on the upgrade, called with a optional version (latest if not specified). See: https://github.com/facebook/react-native/pull/11110

**Comment by mgtitimoli** [comment]
Nice Nicolas, didn't know you had already been working on this, awesome!

Hope they will merge it soon, in any case, [this package](https://www.npmjs.com/package/react-native-git-upgrade) is already there to be downloaded...

I really think you should add some docs to it, and do some announcements, since there are a lot of people that would use it if they know that exist :wink:

**Comment by ncuillery** [comment]
That's the package I initiated before creating the PR to prevent name-squatting. It's empty until the PR is merged.

This repo is referenced from the official documentation since few days:
http://facebook.github.io/react-native/releases/next/docs/upgrading.html
